# Generated by Django 5.2.5 on 2025-09-04 15:22

import encrypted_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0002_encrypteddocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedConfidential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('text', encrypted_fields.fields.EncryptedTextField()),
            ],
        ),
    ]
