# Generated by Django 5.2.5 on 2025-09-05 07:50

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_storage', '0003_encryptedconfidential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptedconfidential',
            name='text',
            field=encrypted_model_fields.fields.EncryptedTextField(),
        ),
    ]
